# Generated by Django 4.1.7 on 2023-04-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhBackAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
